[project]
name = "messages"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "alembic>=1.20.0",
    "fastapi[standard]>=0.141.1",
    "httpx2>=2.13.0",
    "psycopg[binary]>=3.2.10",
    "pytest>=9.1.1",
    "python-dotenv>=1.2.3",
    "sqlalchemy>=2.0.43",
]

[project.scripts]
messages = "messages:main"

[build-system]
requires = ["uv_build>=0.12.5,<0.13.0"]
build-backend = "uv_build"
